# Site wide configuration

title:            phyletica
locale:           en_US
description:      Exploring biodiversification
url:              http://phyletica.org
baseurl:          ""


# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap
  - jekyll/scholar
  - jekyll-gist

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false


# Octopress

# Default extensions
post_ext: md
page_ext: md

# Found in _templates/
post_layout: post
page_layout: page

# Format titles with titlecase?
titlecase: true

scholar:
  style: peerj
  locale: en
  sort_by: year
  order: descending
  use_raw_bibtex_entry: true
  bibtex_filters: latex
  source: ./_bibliography
  bibliography: references.bib
  bibliography_template: bib-link
  replace_strings: true
  join_strings:    true
  details_dir:    bibliography
  details_layout: bibtex.html
  details_link:   Details
  query: "@*"

# Site owner
owner:
  name: Jamie Oaks
  avatar: gravatar.jpg
  bio: "Evolutionary biologist."
  email: phyletica@auburn.edu
  disqus-shortname: phyletica
  twitter: jamoaks
  facebook: #username
  google:
    plus: JamieOaks
    analytics: UA-66934027-1
    verify: pPFT15_I-p4fXVzyqxYJxVfQ64J3BE_OEsbgo_7tahA
    ad-client: 
    ad-slot: 
  bing-verify: 
  github: joaks1
  stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: #username
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  codepen: #username

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]
